name: check-exprtk

on:
  schedule:
    - cron: '00 23 * * 0'
  workflow_dispatch: ~

jobs:

  check-exprtk:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Download exprtk
      run: |
        curl -O https://www.partow.net/downloads/exprtk.zip

    - name: Compute and check SHA256
      id: check
      run: |
        set +e
        sha256sum --check exprtk.zip.sha256sum
        echo "status=$?" >> $GITHUB_OUTPUT
        set -e

    # Check if issue exist with that checksum in title
    - name: Check if issue exist
      if: ${{ steps.check.outputs.status != 0 }}
      id: check-issue
      run: |
        SHASUM=$(sha256sum exprtk.zip | awk '{print $1}')
        echo "shasum=${SHASUM}" >> $GITHUB_OUTPUT
        RES=$(gh issue list --label "New version" --state open --search "${SHASUM:0:8} in:title" | wc -l)
        echo "num_issues=${RES}" >> $GITHUB_OUTPUT

    # When no issue exist, create new one
    - name: Create issue
      if: ${{ steps.check.outputs.status != 0 && steps.check-issue.outputs.num_issues == 0 }}
      env:
        SHASUM: ${{ steps.check-issue.outputs.shasum }}
      run: |
        unzip -o exprtk.zip
        git diff > exprtk.patch
        echo "New version found at date $(date +%Y-%m-%d)" > issue-body.txt
        echo "" >> issue-body.txt
        echo "Checksum of \`exprtk.zip\`:" >> issue-body.txt
        echo "\`\`\`" >> issue-body.txt
        echo $SHASUM >> issue-body.txt
        echo "\`\`\`" >> issue-body.txt
        echo "" >> issue-body.txt
        echo "Diff against commit \`$(git rev-parse --short HEAD)\`:" >> issue-body.txt
        echo "\`\`\`" >> issue-body.txt
        echo $(cat exprtk.patch) >> issue-body.txt
        echo "\`\`\`" >> issue-body.txt
        gh issue create --title "New version: ${SHASUM:0:8} at $(date +%Y-%m-%d)" --label "New version" --body-file issue-body.txt
